version: '3.1'
services:
  nginx:
    container_name: webphp-openresty
    image: webphp:openresty
    build: ./config/openresty/dockerfile/
    hostname: ${NGINX_HOSTNAME}
    ports:
      - "${NGINX_PORT}:80"
    links:
      - "php"
    env_file:
      - ./.env
    volumes:
      - ./config/openresty/logs/:/usr/local/openresty/nginx/logs
      - ./config/openresty/etc/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./config/openresty/etc/conf.d:/usr/local/openresty/nginx/conf/conf.d
      - ./www:/www
    depends_on:
      - php
  php:
    container_name: webphp-php
    image: webphp:php
    build: ./config/php/dockerfile/
    hostname: ${PHP_HOSTNAME}
    env_file:
      - ./.env
    volumes:
      - ./config/php/etc/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/etc/php-fpm.conf:/usr/local/etc/php/fpm/php-fpm.conf
      - ./config/php/etc/php-fpm.d/www.conf:/usr/local/etc/php/fpm/php-fpm.d/www.conf
      - ./config/php/logs/:/var/log/php/
      - ./www:/www
  mongo:
    container_name: webphp-mongo
    image: mongo:3.6
    hostname: ${MONGO_HOSTNAME}
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - ./.env
    volumes:
      - ./config/mongo/etc/mongod.conf:/etc/mongod.conf
      - ./config/mongo/data/:/data/db/
      - ./config/mongo/logs/:/var/log/mongo/
  mysql:
    container_name: webphp-mysql
    image: mysql:8
    hostname: ${MYSQL_HOSTNAME}
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - ./.env
    environment:  
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    volumes:
      - ./config/mysql/etc/mysqld.cnf:/etc/mysql/my.cnf
      - ./config/mysql/data/:/data/db
      - ./config/mysql/init:/docker-entrypoint-initdb.d/
      # - ./config/mysql/logs/error.log:/var/log/mysql/error.log
  redis:
    container_name: webphp-redis
    image: redis:4-alpine
    hostname: ${REDIS_HOSTNAME}
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - ./.env
    volumes:
      - ./config/redis/etc/redis.conf:/etc/redis.conf
      - ./config/redis/data:/data
      - ./config/redis/logs/:/var/log/redis/