version: '3.3'
services:
  mysql-server:
    hostname: mysql-server
    container_name: mysql-server
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      - zabbix
    volumes:
      - /data/mysql/data2:/var/lib/mysql
    command: --character-set-server=utf8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix

  zabbix-web-nginx-mysql:
    hostname: zabbix-web-nginx-mysql
    container_name: zabbix-web-nginx-mysql
    image: zabbix/zabbix-web-nginx-mysql:alpine-3.4.10
    networks:
      - zabbix
    links: 
      - mysql-server:mysql-server
      - zabbix-server:zabbix-server
    ports:
      - 10080:80
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: 123456
      ZBX_SERVER_NAME: web-name
      PHP_TZ: Asia/Shanghai

  zabbix-server:
    hostname: zabbix-server-mysql 
    image: zabbix/zabbix-server-mysql:alpine-3.4.10
    networks:
      - zabbix
    links:
      - mysql-server:mysql-server
    container_name: zabbix-server-mysql 
    ports:
      - 10051:10051
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: 123456

networks:
  zabbix: 
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"